services:
  todo-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    volumes:
      - todo-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  todo-db-data:
