defmodule TodoApp.Repo.Migrations.LinkTodoEntryToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:entries) do
      add :author_id,
          references(:users,
            column: :id,
            name: "entries_author_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:entries, "entries_author_id_fkey")

    alter table(:entries) do
      remove :author_id
    end
  end
end
